from django.conf.urls import url, patterns
from views import *

urlpatterns = patterns('',
    url(r'^$', 'balanced.views.home', name='home'),
    url(r'^ciclos/$', ListCicloView.as_view(), name='ciclos_list'),
    url(r'^ciclos/add/$', CreateCicloView.as_view(), name='ciclos_add'),
    url(r'^ciclos/edit/(?P<pk>\d+)/$', UpdateCicloView.as_view(), name='ciclos_update'),
    url(r'^ciclos/delete/(?P<pk>\d+)/$', DeleteCicloView.as_view(), name='ciclos_delete'),
    url(r'^dimensiones/$', ListDimensionView.as_view(), name='dimensiones_list'),
    url(r'^dimensiones/add/$', CreateDimensionView.as_view(), name='dimensiones_add'),
    url(r'^dimensiones/edit/(?P<pk>\d+)/$', UpdateDimensionView.as_view(), name='dimensiones_update'),
    url(r'^dimensiones/delete/(?P<pk>\d+)/$', DeleteDimensionView.as_view(), name='dimensiones_delete'),
    url(r'^objetivos/$', 'balanced.views.ListObjetivoView', name='objetivos_list'),
    url(r'^objetivos/edit/(?P<pk>\d+)/$', UpdateObjetivoView.as_view(), name='objetivos_update'),
    url(r'^objetivos/view/(?P<pk>\d+)/$', 'balanced.views.ViewObjetivo', name='objetivos_view'),
    url(r'^proyectos/$', 'balanced.views.ListProyectoView', name='proyectos_list'),
    url(r'^proyectos/add/$', CreateProyectoView.as_view(), name='proyecto_add'),
    url(r'^proyectos/edit/(?P<pk>\d+)/$', UpdateProyectoView.as_view(), name='proyectos_update'),
    url(r'^proyectos/delete/(?P<pk>\d+)/$', DeleteProyectoView.as_view(), name='proyectos_delete'),
    url(r'^dashboard/(?P<pk>\d+)/$', 'balanced.views.DetalleDimension', name='detalle_dimension'),
    url(r'^carga_observacion_proyecto/(?P<id>\d+)$', 'balanced.views.carga_observacion', name='cargar_observacion'),
    url(r'^carga_evolucion_proyecto/(?P<id>\d+)/$', 'balanced.views.cargar_proyecto', name='salida'),
    url(r'^observaciones/add/$', 'balanced.views.agregar_observacion', name='observaciones_add'),
    url(r'^carga_acumulado/$', 'balanced.views.carga_acumulado', name='carga_acumulado'),
    url(r'^revisiones/$', 'balanced.views.revisiones', name='revisiones'),
    url(r'^carga_revision/(?P<id>\d+)/$', 'balanced.views.detalle_revision', name='revision'),
    url(r'^objetivos_filtro/(?P<id>\d+)/$', 'balanced.views.filtrar_objetivos', name='obj_filtro'),
    url(r'^revisiones/add/$', 'balanced.views.agregar_revision', name='revisiones_add'),
    url(r'^carga_check/(?P<id>\d+)/$', 'balanced.views.check_revision', name='check'),
    url(r'^check/add/$', 'balanced.views.agregar_check', name='check_add'),
)